language: node_js
node_js:
  - 'node'
cache:
  directories:
    - "node_modules"
script:
  - parcel build index.html
sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ${TRAVIS_BUILD_DIR}/dist
  on:
    branch: master
