language: node_js
node_js:
  - 'node'
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - parcel build index.html
sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
